services:
  - type: worker
    env: node
    name: supabase-to-discord
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    plan: starter
    envVars:
      - key: TRIGGER_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: SUPABASE_TABLE
        sync: false